---
--- Generated by Luanalysis
--- Created by Kapl.
--- DateTime: 2024/4/22 13:21
---
package.cpath = package.cpath .. ';C:/Users/Kapl/AppData/Roaming/JetBrains/Rider2023.1/plugins/EmmyLua/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 20888)

require("Library/Object")
require("Library/NameSpace")
-- 初始化类
require("App/Manager/UIManager/UIManager")

-- 初始化GameManager
require("App/Manager/GameManager")