---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/15 23:23
---

package.cpath = package.cpath .. ';C:/Users/Kapl/AppData/Roaming/JetBrains/Rider2023.1/plugins/EmmyLua/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 24088)

require("Library/Object")
require("Library/NameSpace")
-- 初始化类
require("App/Manager/UIManager")
