---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/7 19:03
---
require('App/Model/MapDataModel')
require('App/Model/GameObjectModel')
require('App/Manager/Spawner')
require('App/Object/Map')
require('App/Manager/BossGameDataManager')

BossGameManager = Object:SubClass('BossGameManager')

BossGameManager.cs = nil

BossGameManager.gameDataManager = nil
BossGameManager.map = nil
BossGameManager.mapData = nil
BossGameManager.spawner = nil

BossGameManager.money = nil

BossGameManager.isStop = true
BossGameManager.isPause = true

BossGameManager.killMonsterCount = 0
BossGameManager.getAllmoney = 0

function BossGameManager:Init()
    -- 初始化场景管理器
    UIManager:ShowPanel('BossPanel', EUILayers.Middle)
    self.cs = LuaSceneManager()
    GameManager.Instance:SetSceneManager(self.cs)
    self:InitCsAction()

    self.gameDataManager = BossGameDataManager
    self:SetSceneDataManager(BossGameDataManager.script)
    
end

function BossGameManager:InitCsAction()
    -- 添加回调函数
    self.cs.onGetSpawnerAction = function ()
        return self:GetSpawner()
    end
    self.cs.onSetSpawnerAction = function(spawner)
        self:SetSpwaner(spawner)
    end
    self.cs.onSetSceneDataManagerAction = function(sceneDataManager)
        self:SetSceneDataManager(sceneDataManager)
    end
    self.cs.onInitGameAction = function(levelID)
        self:InitGame(levelID)
    end
    self.cs.onStartGameAction = function()
        self:StartGame()
    end
    self.cs.onPauseGameAction = function()
        self:PauseGame()
    end
    self.cs.onResumeGameAction = function()
        self:ResumeGame()
    end
    self.cs.onRestartGameAction = function()
        self:RestartGame()
    end
    self.cs.onEndGameAction = function()
        self:EndGame()
    end
    self.cs.onGameOverAction = function()
        self:GameOver()
    end
    self.cs.onGameWinAction = function()
        self:GameWin()
    end
    self.cs.onNextLevelAction = function()
        self:NextLevel()
    end
    self.cs.onSetSpeedUpAction = function(isSpeedUp)
        self:SetSpeedUp(isSpeedUp)
    end
    self.cs.onIsPauseFunc = function()
        return self:IsPause()
    end
    self.cs.onIsStopFunc = function()
        return self:IsStop()
    end
    self.cs.onSetFireTargetAction = function(target)
        self:SetFireTarget(target)
    end
    self.cs.onCancelFireAction = function()
        self:CancelFire()
    end
    self.cs.onGetMoneyFunc = function()
        return self:GetMoney()
    end
    self.cs.onUpdateKillMonsterCountAction = function(v)
        self:UpdateKillMonsterCount(v)
    end
    self.cs.onUpdateMoneyAction = function(v)
        self:UpdateMoney(v)
    end
end

function BossGameManager:InitGame(levelID)
    self.isStop = true
    self.isPause = true
    self.getAllmoney = 0
    self.killMonsterCount = 0

    -- 加载地图数据
    self.mapData = self.gameDataManager:Load('AB/Data/BossMap' .. levelID)
    -- 初始化
    if self.map == nil then
        self.map = Map:New()
        self.map:InitLua(self.mapData)
    end

    if self.spawner == nil then
        self.spawner = Spawner:New()
        self.spawner:InitLua(self.mapData)
    end
    
    self.money = self.mapData.money
    GameManager.Instance:StopMusic()
    -- UI
    local panel = UIManager:ShowPanel('BossGamePanel', EUILayers.Bottom)
    panel:UpdateTime(240)
    self:UpdateMoney(self.money)
    -- 添加事件
    GameManager.Instance.eventCenter:RemoveEvent('JudgeWin')
    GameManager.Instance.eventCenter:AddEventListener('JudgeWin', function ()
        self:JudgeWin()
    end)
end

function BossGameManager:JudgeWin()
    print('JudgeWin')
end

function BossGameManager:StartGame()
    self.isStop = false
    self.isPause = false
    self.spawner:StartSpawn()
    UIManager:GetPanel('BossGamePanel'):StartCountDown(240)
end

function BossGameManager:PauseGame()
    self.isPause = true
    self.spawner:PauseWaves()
end

function BossGameManager:ResumeGame()
    self.isPause = false
    self.spawner:ResumeWaves()
end

function BossGameManager:RestartGame()
    print('restart')
end

function BossGameManager:EndGame()
    print('end')
end

function BossGameManager:GameOver()
    print('game over')
end

function BossGameManager:GameWin()
    print('game win')
end

function BossGameManager:NextLevel()
    print('next level')
end

-- 获取和设置变量
function BossGameManager:SetSpeedUp()
    print('set speed up')
end

function BossGameManager:IsPause()
    return self.isPause
end
function BossGameManager:IsStop()
    return self.isStop
end
function BossGameManager:SetSpwaner(spawner)
    self.cs.Spawner = spawner
    self.spawner = spawner
end

function BossGameManager:SetSceneDataManager(manager)
    self.sceneDataManager = manager
end

function BossGameManager:GetSceneDataManager()
    return self.sceneDataManager
end

function BossGameManager:GetMoney()
    return self.money
end

function BossGameManager:GetSpawner()
    return self.spawner.cs
end

-- 更新数据
function BossGameManager:UpdateKillMonsterCount(v)
    self.killMonsterCount = self.killMonsterCount + v
end

function BossGameManager:UpdateMoney(v)
    self.money = self.money + v
    -- 通知面板更新数据
    UIManager:GetPanel('BossGamePanel'):UpdateMoney(self.money)
end

