---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/7 19:03
---
require('App/Model/MapDataModel')
require('App/Model/GameObjectModel')
require('App/Manager/Spawner')
require('App/Object/Map')
require('App/Manager/BossGameDataManager')

BossGameManager = Object:SubClass('BossGameManager')

BossGameManager.script = nil

BossGameManager.gameDataManager = nil
BossGameManager.map = nil
BossGameManager.mapData = nil
BossGameManager.spawner = nil

BossGameManager.money = nil

BossGameManager.isStop = true
BossGameManager.isPause = true

function BossGameManager:Init()
    -- 初始化场景管理器
    UIManager:ShowPanel('BossPanel', EUILayers.Middle)
    self.script = LuaSceneManager()
    GameManager.Instance:SetSceneManager(self.script)
    self:InitCsAction()

    self.gameDataManager = BossGameDataManager
    self:SetSceneDataManager(BossGameDataManager.script)

end

function BossGameManager:InitCsAction()
    -- 添加回调函数
    self.script.onSetSpawnerAction = function(spawner)
        self:SetSpwaner(spawner)
    end
    self.script.onSetSceneDataManagerAction = function(sceneDataManager)
        self:SetSceneDataManager(sceneDataManager)
    end
    self.script.onInitGameAction = function(levelID)
        self:InitGame(levelID)
    end
    self.script.onStartGameAction = function()
        self:StartGame()
    end
    self.script.onPauseGameAction = function()
        self:PauseGame()
    end
    self.script.onResumeGameAction = function()
        self:ResumeGame()
    end
    self.script.onRestartGameAction = function()
        self:RestartGame()
    end
    self.script.onEndGameAction = function()
        self:EndGame()
    end
    self.script.onGameOverAction = function()
        self:GameOver()
    end
    self.script.onGameWinAction = function()
        self:GameWin()
    end
    self.script.onNextLevelAction = function()
        self:NextLevel()
    end
    self.script.onSetSpeedUpAction = function(isSpeedUp)
        self:SetSpeedUp(isSpeedUp)
    end
    self.script.onIsPauseFunc = function()
        return self:IsPause()
    end
    self.script.onIsStopFunc = function()
        return self:IsStop()
    end
    self.script.onSetFireTargetAction = function(target)
        self:SetFireTarget(target)
    end
    self.script.onCancelFireAction = function()
        self:CancelFire()
    end
    self.script.onGetMoneyFunc = function()
        return self:GetMoney()
    end
    self.script.onUpdateKillMonsterCountAction = function(v)
        self:UpdateKillMonsterCount(v)
    end
    self.script.onUpdateMoneyAction = function(v)
        self:UpdateMoney(v)
    end
end



function BossGameManager:InitGame(levelID)
    self.isStop = true
    self.isPause = true

    -- 加载地图数据
    self.mapData = self.gameDataManager:Load('AB/Data/BossMap' .. levelID)
    -- 初始化
    if self.map == nil then
        self.map = Map:New()
        self.map:InitLua(self.mapData)
    end

    if self.spawner == nil then
        self.spawner = Spawner:New()
        self.spawner:InitLua(self.mapData)
    end
    
    self.money = self.mapData.money
    GameManager.Instance:StopMusic()
    -- UI
    UIManager:ShowPanel('BossGamePanel', EUILayers.Bottom)

end

function BossGameManager:StartGame()
    print('start')
    self.isStop = false
    self.isPause = false
    self.spawner:StartSpawn()
end

function BossGameManager:PauseGame()
    self.isPause = true
    self.spawner:PauseWaves()
end

function BossGameManager:ResumeGame()
    self.isPause = false
    self.spawner:ResumeWaves()
end

function BossGameManager:RestartGame()
    print('restart')
end

function BossGameManager:EndGame()
    print('end')
end

function BossGameManager:GameOver()
    print('game over')
end

function BossGameManager:GameWin()
    print('game win')
end

function BossGameManager:NextLevel()
    print('next level')
end

function BossGameManager:SetSpeedUp()
    print('set speed up')
end

function BossGameManager:IsPause()
    return self.isPause
end
function BossGameManager:IsStop()
    return self.isStop
end
function BossGameManager:SetSpwaner(spawner)
    self.script.Spawner = spawner
    self.spawner = spawner
end

function BossGameManager:SetSceneDataManager(manager)
    self.sceneDataManager = manager
end

function BossGameManager:GetSceneDataManager()
    return self.sceneDataManager
end



