---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/7 19:03
---
require('App/Model/MapDataModel')
require('App/Model/GameObjectModel')
require('App/Manager/Spawner')
require('App/View/Map')

BossGameManager = Object:SubClass('BossGameManager')

BossGameManager.mapData = nil

BossGameManager.mapDataModel = MapDataModel
BossGameManager.gameObjectModel = GameObjectModel
BossGameManager.spawner = Spawner
BossGameManager.map = Map

--Game
BossGameManager.money = 0

function BossGameManager.Init(self, mapIndex)
    self.mapData = self.mapDataModel:Load(mapIndex)
    self.map:Init(comp.gameObject, self.mapData)

    self.spawner:Init(self.mapData)
    GameManager.Instance.spawner = self.spawner.comp

    self.money = self.mapData.money
    self:Start()
end

function BossGameManager.Start(self)
    GameManager.Instance.stop = false
end
