---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/15 23:03
---

require("App/UI/BasePanel")
require("App/UI/BeginPanel")
require("App/UI/BossPanel")


UIManager = Object:SubClass("UIManager")

UIManager.panelDic = {}

function UIManager:ShowPanel(panelName)
    local panel
    -- 加载面板预设体
    if self.panelDic[panelName] == nil then
        local panelObj = GameObject.Instantiate(Resources.Load("UI/" .. panelName), CS.UIManager.Instance.Bottom)
        -- 设置
        panelObj.transform.localScale = Vector3.one
        -- 绑定到lua脚本
        panel = _G[panelName]
        panel.panelObj = panelObj
        -- 保存到字典
        self.panelDic[panelName] = panel
        -- 调用Show方法
        panel:Show()
    end

    return self.panelDic[panelName]
end

function UIManager:HidePanel(panelName)
    -- 删除面板
    if self.panelDic[panelName] ~= nil then
        local panel = self.panelDic[panelName]
        panel:Hide()
        GameObject.Destroy(panel.panelObj)
        
        self.panelDic[panelName] = nil
    end
end

function UIManager:GetPanel(panelName)
    return self.panelDic[panelName]
end