---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/15 17:38
---

BossPanel = BasePanel:SubClass("BossPanel")

BossPanel.btnHome = nil
BossPanel.btnHelp = nil

BossPanel.namesTsf = nil -- 用于显示怪物名字Transform
BossPanel.hpsTsf = nil   -- 用于显示怪物血量Transform
BossPanel.limitTimeTsf = nil -- 用于显示限时Transform
BossPanel.namesList = {} -- 怪物名字列表
BossPanel.hpsList = {}   -- 怪物血量列表
BossPanel.limitTimeList = {} -- 限时列表

function BossPanel:Init()
    self.btnHome = self.panelObj.transform:Find("ButtonHome"):GetComponent("Button")
    self.btnBegin = self.panelObj.transform:Find("ButtonHelp"):GetComponent("Button")

    self.btnHome.onClick:AddListener(function()
        UIManager:HidePanel("BossPanel")
        CS.GameFacade.Instance:SendNotification("ShowBeginPanel")
    end)

    self.btnBegin.onClick:AddListener(function()
        UIManager:HidePanel("BossPanel")
        CS.GameFacade.Instance:SendNotification("ShowHelpPanel", false)
    end)

    self.namesTsf = self.panelObj.transform:Find("MonstersName")
    self.hpsTsf = self.panelObj.transform:Find("ImageHp"):Find("HpNums")
    self.limitTimeTsf = self.panelObj.transform:Find("LimitTime")
    -- 获取怪物名字和血量list
    for i = 0, self.namesTsf.childCount - 1 do
        self.namesList[i] = self.namesTsf:GetChild(i)
        self.namesList[i].gameObject:SetActive(false)
    end

    for i = 0, self.hpsTsf.childCount - 1 do
        self.hpsList[i] = self.hpsTsf:GetChild(i)
        self.hpsList[i].gameObject:SetActive(false)
    end
    
    for i = 0, self.limitTimeTsf.childCount - 1 do
        self.limitTimeList[i] = self.limitTimeTsf:GetChild(i)
        self.limitTimeList[i].gameObject:SetActive(false)
    end

    --默认显示第一个
    self.namesList[0].gameObject:SetActive(true)
    self.hpsList[0].gameObject:SetActive(true)
    self.limitTimeList[0].gameObject:SetActive(true)
end
