---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kapl.
--- DateTime: 2024/4/15 17:38
---

BossPanel = BasePanel:SubClass('BossPanel')

BossPanel.btnHome = nil
BossPanel.btnHelp = nil
BossPanel.btnStart = nil

BossPanel.namesTsf = nil -- 用于显示怪物名字 Transform
BossPanel.hpsTsf = nil -- 用于显示怪物血量 Transform
BossPanel.limitTimeTsf = nil -- 用于显示限时 Transform
BossPanel.namesList = {} -- 怪物名字列表
BossPanel.hpsList = {} -- 怪物血量列表
BossPanel.limitTimeList = {} -- 限时列表

-- 翻页效果相关
BossPanel.sr = nil

BossPanel.slidingThreshold = 150 -- 滑动阈值
BossPanel.offSetMouseX = 0 -- 鼠标拖动的X坐标
BossPanel.index = 1
BossPanel.totalCount = 3
BossPanel.speed = 0.1

-- Unity回调相关
BossPanel.monoScripts = nil
BossPanel.mouseInterfaceClass = nil

function BossPanel.Init(self)
    -- 查找控件
    self.btnHome = self.panelObj.transform:Find('ButtonHome'):GetComponent('Button')
    self.btnHelp = self.panelObj.transform:Find('ButtonHelp'):GetComponent('Button')
    self.btnStart = self.panelObj.transform:Find('ButtonStart'):GetComponent('Button')
    self.namesTsf = self.panelObj.transform:Find('MonstersName')
    self.hpsTsf = self.panelObj.transform:Find('ImageHp'):Find('HpNums')
    self.limitTimeTsf = self.panelObj.transform:Find('LimitTime')
    self.sr = self.panelObj.transform:Find('Monsters'):Find('Scroll View'):GetComponent(typeof(ScrollRect))

    -- 监听函数
    self.btnHome.onClick:AddListener(
        function()
            UIManager:HidePanel('BossPanel')
            CS.GameFacade.Instance:SendNotification('ShowBeginPanel')
        end
    )

    self.btnHelp.onClick:AddListener(
        function()
            UIManager:HidePanel('BossPanel')
            CS.GameFacade.Instance:SendNotification('ShowHelpPanel', false)
        end
    )

    self.btnStart.onClick:AddListener(
        function()
            GameManager.Instance.uiManager:Hide('BeginPanel', false)
            UIManager:HidePanel('BossPanel', false)
            GameManager.Instance:LoadGameScene('BossGameScene', self.index)
        end
    )

    -- 获取怪物名字和血量list
    for i = 0, self.namesTsf.childCount - 1 do
        self.namesList[i] = self.namesTsf:GetChild(i)
        self.namesList[i].gameObject:SetActive(false)
    end

    for i = 0, self.hpsTsf.childCount - 1 do
        self.hpsList[i] = self.hpsTsf:GetChild(i)
        self.hpsList[i].gameObject:SetActive(false)
    end

    for i = 0, self.limitTimeTsf.childCount - 1 do
        self.limitTimeList[i] = self.limitTimeTsf:GetChild(i)
        self.limitTimeList[i].gameObject:SetActive(false)
    end

    --默认显示第一个
    self.namesList[0].gameObject:SetActive(true)
    self.hpsList[0].gameObject:SetActive(true)
    self.limitTimeList[0].gameObject:SetActive(true)

    -- 添加UI控件回调脚本
    self.mouseInterfaceClass = self.sr.gameObject:AddComponent(typeof(UIInterfaceClass))
    self.mouseInterfaceClass.onBeginDragAction = function(eventData)
        self:OnBeginDrag(eventData)
    end
    self.mouseInterfaceClass.onEndDragAction = function(eventData)
        self:OnEndDrag(eventData)
    end
    -- 添加Mono脚本
    self.monoScripts = self.panelObj:AddComponent(typeof(MonoScript))
    self.monoScripts.onUpdateAction = function()
        self:Update()
    end
end

function BossPanel:Hide()
    self.__base:Hide()
end

function BossPanel:Update()
    self.sr.horizontalNormalizedPosition =
        Mathf.Lerp(self.sr.horizontalNormalizedPosition, (self.index - 1) / (self.totalCount - 1), self.speed)
end

-- 开始拖动
function BossPanel:OnBeginDrag(eventData)
    self.offSetMouseX = eventData.position.x
end

-- 结束拖动
function BossPanel:OnEndDrag(eventData)
    local offSetX = eventData.position.x - self.offSetMouseX
    if offSetX > self.slidingThreshold then
        self:LastPage()
    elseif offSetX < -self.slidingThreshold then
        self:NextPage()
    end
end

function BossPanel:NextPage()
    self.index = self.index + 1
    if self.index > self.totalCount then
        self.index = self.totalCount
    end

    self:UpdateInfo()
end

function BossPanel:LastPage()
    self.index = self.index - 1
    if self.index < 1 then
        self.index = 1
    end

    self:UpdateInfo()
end

function BossPanel:UpdateInfo()
    -- 更新怪物名字和血量
    for i = 0, self.namesTsf.childCount - 1 do
        self.namesList[i].gameObject:SetActive(false)
    end

    for i = 0, self.hpsTsf.childCount - 1 do
        self.hpsList[i].gameObject:SetActive(false)
    end

    for i = 0, self.limitTimeTsf.childCount - 1 do
        self.limitTimeList[i].gameObject:SetActive(false)
    end

    self.namesList[self.index - 1].gameObject:SetActive(true)
    self.hpsList[self.index - 1].gameObject:SetActive(true)
    self.limitTimeList[self.index - 1].gameObject:SetActive(true)
end
